# Generated by Django 2.2.7 on 2020-01-04 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='oluşturulma zamanı'),
            preserve_default=False,
        ),
    ]
